# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rspec-rails` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: strict

module RSpec; end
module RSpec::Rails; end

module RSpec::Rails::FeatureCheck
  private

  def can_check_pending_migrations?; end
  def can_maintain_test_schema?; end
  def has_1_9_hash_syntax?; end
  def has_action_mailer?; end
  def has_action_mailer_preview?; end
  def has_action_mailer_show_preview?; end
  def has_active_job?; end
  def has_active_record?; end
  def has_active_record_migration?; end
  def has_file_fixture?; end
  def type_metatag(type); end

  class << self
    def can_check_pending_migrations?; end
    def can_maintain_test_schema?; end
    def has_1_9_hash_syntax?; end
    def has_action_mailer?; end
    def has_action_mailer_preview?; end
    def has_action_mailer_show_preview?; end
    def has_active_job?; end
    def has_active_record?; end
    def has_active_record_migration?; end
    def has_file_fixture?; end
    def type_metatag(type); end
  end
end

class RSpec::Rails::Railtie < ::Rails::Railtie
  private

  def config_default_preview_path(options); end
  def config_preview_path?(options); end
  def setup_preview_path(app); end
  def supports_action_mailer_previews?(config); end
end
