version: '2'
volumes:
  pg-data:
services:
  server:
    build: .
    restart: always
    ports:
      - "3009:3000"
    depends_on:
      - db
    environment:
      BILL_BUCK_GENERATOR_DATABASE_HOST: db
      BILL_BUCK_GENERATOR_DATABASE_USER: postgres
      BILL_BUCK_GENERATOR_DATABASE_PASSWORD: password
  db:
    image: postgres:alpine
    volumes:
      - 'pg-data:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password