# typed: strong
# This is an autogenerated file for Rails' mailers.
# Please rerun bundle exec rake rails_rbi:mailers to regenerate.
class BillMailer
  sig do
    params(
      to_name: T.untyped,
      to_email: T.untyped,
      from: T.untyped,
      for_message: T.untyped,
      count: T.untyped
    ).returns(ActionMailer::MessageDelivery)
  end
  def self.bill(to_name:, to_email:, from:, for_message:, count:); end
end
