# typed: strong
# This is an autogenerated file for Rails' mailers.
# Please rerun bundle exec rake rails_rbi:mailers to regenerate.
class BillMailer
  sig { params(buck_wad: BuckWad, to_email: String, from_email: String).returns(ActionMailer::MessageDelivery) }
  def self.bill(buck_wad:, to_email:, from_email:); end
end
