# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: strict

module ::RuboCop::AST::Ext::Range; end
module ::Spring; end
module T::Private::Methods::Signature; end
