# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: strict

module ::Spring; end
module Haml::AttributeParser; end
module Haml::Parser::SPECIAL_CHARACTERS; end
module Haml::VERSION; end
module RBS::Parser; end
module RBS::Parser::KEYWORDS_RE; end
module T::Private::Methods::Signature; end
module Tapioca::Gemfile::Gem::Specification; end
