name: Prettier

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - run: ls -la
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0
      
      - run: ls -la
      
      # until plugin support is added to this action (https://github.com/creyD/prettier_action/issues/22) we can't prettier ruby :(
      - name: Prettify code
        uses: creyD/prettier_action@v3.1
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write .
          only_changed: True
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: ls -la
      - uses: bahmutov/npm-install@v1
      - name: Run prettier on ruby files
        run: yarn run prettier -c $(git ls-files | grep "\.rb$" | xargs)
