name: Ruby

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-18.04 # use 18 because version 20 didn't have helvetica font

    env:
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres
      RAILS_ENV: test

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: ${{ env.PGPASSWORD }}
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out files
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install ghostscript
        run: sudo apt-get install ghostscript

#     - name: Install PostgreSQL client
#       uses: ryankurte/action-apt@v0.2.0
#       with:
#         packages: libpq-dev

      - name: Install bundle
        run: bundle install --jobs 4 --retry 3
      # install yarn dependencies
      - uses: bahmutov/npm-install@v1

      - name: Setup database
        run: bin/rails db:setup

      - name: Run tests
        run: bin/rspec
